[mgr]
linemode = "size"

[opener]
edit = [
	{ run = "vim %s", for = "windows", block = true },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

